.Dd 2023-05-07
.Dt PING 1
.Os abase
.Sh NAME
.Nm ping
.Nd tests reachability of a host on the network
.Sh SYNOPSIS
.Nm
{destination}
.Sh DESCRIPTION
.Nm
ping sends an ICMP ECHO_REQUEST to a host and waits for the answer by
the host. It prints each second information (if the host is reachable)
and terminates and prints statistics if the user pressed Ctrl-C.
